version: "3.8"

services:

  client:
    image: "larsvandersangen/multi-client"
    mem_limit: 128m
    hostname: client

  server:
    image: "larsvandersangen/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: "larsvandersangen/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: "larsvandersangen/multi-nginx"
    memory: 128m
    hostname: nginx
    ports:
      - "80:80"
